keywords: 

since: 

logo: 

favicon: false

nav:
  - title: 归档
    url: archives/index.html
    icon: fa-archive
    description: 
  - title: 关于
    url: about/index.html
    icon: fa-user
    description: 

notice:
  - "**Notice** one"
  - "~~Notice~~ two"

global_navigation: true

sidebar: true

# Register at https://disqus.com/api/applications to get disqus_api_key
# Use the API Key, not the API Secret
disqus_shortname: 
disqus_api_key: 

search: true

busuanzi: true

tag_number: 25
full_content: false

# Provided colors: red, green, blue, purple
color_theme: blue

mathjax: true

# Available: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
creative_commons: by-sa

toc:
  collapse: false

sns: 
  github: 
  twitter:
  facebook:
  linkedin:
  googleplus_id: 
  steam_id:
  weibo:
  zhihu: 
  tieba: 

buttons:
  base: true
  border: false
  borderless: false
  raised: false
  3d: false
  glowing: false
  dropdown: false
  group: false
  wrapper: false
  shadow: false

links:
  - title: Friend1
    url: https://www.friend1.com
    description: My only friend
